import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Top Programming Languages By CodeStats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Top 10 Programming-Languages of{" "}
          <a
            href="https://github.com/maorun"
            target="_blank"
            rel="noopener noreferrer"
          >
            maorun
          </a>
        </h1>
        <Image
          height={400}
          width={600}
          src="/api/codestats/maorun/top/10"
          alt="chart"
        />
      </main>
    </div>
  );
};

export default Home;
